model:
  target: control_lora.models.LoRAContainer
  params:
    block_out_channels: [320, 640, 1280, 1280]
    cross_attention_dims: [
      [null, 768, null, 768, null, 768, null, 768, null, 768], 
      [null, 768, null, 768, null, 768, null, 768, null, 768], 
      [null, 768, null, 768, null, 768, null, 768, null, 768], 
      [null, 768]
    ]
    rank: 4

dataset:
  target: control_lora.datasets.BaseDataset
  params:
    path: data/highcwu-v1 # it actually read images in `data/highcwu-v1/train/portrait of male HighCWu`
    is_imagefolder: true
    instance_text: portrait of male HighCWu
    skip_guide: true
    resolution: 512
    enable_zoom_out: true
    enable_zoom_in: true

trainer:
  target: control_lora.commands.trainer.Trainer
  params:
    pretrained_model_name_or_path: runwayml/stable-diffusion-v1-5
    output_dir: ckpts/sd-v1-5-lora-highcwu-v1
    train_batch_size: 1
    gradient_accumulation_steps: 1
    checkpointing_steps: 200
    sample_in_checkpointing: true
    resume_from_checkpoint: latest
    learning_rate: 0.0001
    report_to: wandb
    lr_scheduler: constant
    lr_warmup_steps: 0
    max_train_steps: 2000
    validation_prompt: portrait of female HighCWu as a cute pink hair girl
    validation_epochs: -1
    mixed_precision: 'fp16'
    enable_xformers_memory_efficient_attention: false
    seed: 0
    num_sampling_images: 100
